# Generated by Django 5.2.5 on 2025-09-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='about/banner/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('section1_image', models.ImageField(blank=True, null=True, upload_to='about/section1/')),
                ('section1_text', models.TextField(blank=True, null=True)),
                ('section2_image', models.ImageField(blank=True, null=True, upload_to='about/section2/')),
                ('section2_text', models.TextField(blank=True, null=True)),
                ('row_image_1', models.ImageField(blank=True, null=True, upload_to='about/row/')),
                ('row_image_2', models.ImageField(blank=True, null=True, upload_to='about/row/')),
                ('row_image_3', models.ImageField(blank=True, null=True, upload_to='about/row/')),
                ('row_image_4', models.ImageField(blank=True, null=True, upload_to='about/row/')),
            ],
        ),
    ]
