# Generated by Django 5.2.5 on 2025-09-02 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_blogcategory_siteasset_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='row_image_1',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='row_image_2',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='row_image_3',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='row_image_4',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='section1_image',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='section1_text',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='section2_image',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='section2_text',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='banner_title',
            field=models.CharField(default='About TRACO', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/mission/'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_title',
            field=models.CharField(default='Our Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/vision/'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_title',
            field=models.CharField(default='Our Vision', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='who_para1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='who_para2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='who_title',
            field=models.CharField(default='Who are We?', max_length=200),
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='about/why_icons/')),
                ('title', models.CharField(max_length=200)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_items', to='trading.aboutcontent')),
            ],
        ),
    ]
