# Generated by Django 5.2.5 on 2025-09-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_blogimage_blogtext_heroimage_herotext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='trading.blogimage'),
        ),
    ]
