# Generated by Django 5.2.5 on 2025-09-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_blogpost_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='card_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='card_text',
        ),
        migrations.DeleteModel(
            name='HeroImage',
        ),
        migrations.DeleteModel(
            name='HeroText',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='BlogText',
        ),
    ]
