# Generated by Django 5.2.5 on 2025-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_remove_blogpost_category_remove_blogpost_card_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Don’t Just Gain info', max_length=200)),
                ('subtitle', models.CharField(default='Build Knowledge', max_length=200)),
                ('description', models.TextField(default='Whether you’re a new investor or a market expert, we’ve got something for everyone at the TRACO blog')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('sparkle', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
            options={
                'verbose_name': 'Blog Hero_Section',
                'verbose_name_plural': 'Blog Hero_Section',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('stocks', 'Stocks'), ('mutual', 'Mutual Funds'), ('finance', 'Personal Finance'), ('futures', 'Futures & Options')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.TextField()),
                ('read_time', models.CharField(default='5 Mins Read', max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_posts/')),
            ],
            options={
                'verbose_name': 'Blog Posts',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='BlogTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_key', models.CharField(choices=[('stocks', 'Stocks'), ('mutual', 'Mutual Funds'), ('finance', 'Personal Finance'), ('futures', 'Futures & Options')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Blog tabs',
                'verbose_name_plural': 'Blog tabs',
            },
        ),
    ]
