# Generated by Django 5.2.5 on 2025-09-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_bannersection_communitysection_homesection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerSection',
        ),
        migrations.DeleteModel(
            name='CommunitySection',
        ),
        migrations.DeleteModel(
            name='HomeSection',
        ),
        migrations.DeleteModel(
            name='HomeSection2',
        ),
        migrations.DeleteModel(
            name='HomeSection3',
        ),
        migrations.DeleteModel(
            name='HomeSection4',
        ),
        migrations.RemoveField(
            model_name='partnerbenefit',
            name='section',
        ),
        migrations.DeleteModel(
            name='PartnerLead',
        ),
        migrations.DeleteModel(
            name='PartnerSection',
        ),
        migrations.DeleteModel(
            name='PartnerBenefit',
        ),
        migrations.DeleteModel(
            name='PartnerBenefitsSection',
        ),
    ]
