# Generated by Django 5.2.5 on 2025-09-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_delete_bannersection_delete_communitysection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogHero',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='BlogTab',
        ),
    ]
