# Generated by Django 5.2.5 on 2025-09-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_bannersection_communitysection_homesection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerSection',
        ),
        migrations.DeleteModel(
            name='CommunitySection',
        ),
        migrations.DeleteModel(
            name='HomeSection',
        ),
        migrations.DeleteModel(
            name='HomeSection2',
        ),
        migrations.DeleteModel(
            name='HomeSection3',
        ),
        migrations.DeleteModel(
            name='HomeSection4',
        ),
    ]
