# Generated by Django 5.2.5 on 2025-09-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Our Platform', max_length=200)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='banner/')),
            ],
            options={
                'verbose_name': 'Home Dashboard_Section',
                'verbose_name_plural': 'Home Dashbord_Section',
            },
        ),
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Build a Strong Community', max_length=200)),
                ('description', models.TextField(default='Join a global network of passionate traders...')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='community/')),
            ],
            options={
                'verbose_name': 'Home community_Section',
                'verbose_name_plural': 'Home community_Section',
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Build Confidence With Every Single Trade.', max_length=200)),
                ('title1', models.CharField(default='Invest for Your Future', max_length=200)),
                ('subtitle', models.CharField(default='Keep Your Money Safe !!!!', max_length=200)),
                ('description', models.CharField(default='Your Trading Journey Started Here….', max_length=250)),
                ('realtime_users_count', models.CharField(default='500+', max_length=50)),
                ('realtime_users_label', models.CharField(default='Realtime Users', max_length=100)),
                ('bg_banner', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('banner_user', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('vertical_bar', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('arrow', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('user1', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('user2', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('user3', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('user4', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('user5', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Hero_Section',
                'verbose_name_plural': 'Home Hero_Section',
            },
        ),
        migrations.CreateModel(
            name='HomeSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph1', models.TextField(blank=True, help_text='First paragraph (normal text)', null=True)),
                ('paragraph2', models.TextField(blank=True, help_text='Second paragraph (highlighted in green)', null=True)),
                ('paragraph3', models.TextField(blank=True, help_text='Third paragraph (footer text)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('image20years', models.ImageField(blank=True, null=True, upload_to='homepage/')),
            ],
            options={
                'verbose_name': 'Home Experience_Section',
                'verbose_name_plural': 'Home Experience_Section',
            },
        ),
        migrations.CreateModel(
            name='HomeSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(help_text='Step number like 01, 02, 03', max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('highlight', models.BooleanField(default=False, help_text='Mark this step as highlighted (green middle box)')),
            ],
            options={
                'verbose_name': 'Home Features_Section',
                'verbose_name_plural': 'Home Features_Section',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='How it Works?', max_length=200)),
                ('apply_title', models.CharField(default='Apply', max_length=100)),
                ('apply_desc', models.TextField(default='Join thousands of traders who trust our platform every day.')),
                ('apply_img', models.ImageField(blank=True, null=True, upload_to='section4/')),
                ('assess_title', models.CharField(default='Assessment', max_length=100)),
                ('assess_desc', models.TextField(default='Take our short assessment to discover your trading style, risk tolerance, and the tools that fit you best.')),
                ('assess_img', models.ImageField(blank=True, null=True, upload_to='section4/')),
                ('fund_title', models.CharField(default='Get Funded', max_length=100)),
                ('fund_desc', models.TextField(default='Trade with our capital and keep up to 90% of the profits.')),
                ('fund_img', models.ImageField(blank=True, null=True, upload_to='section4/')),
                ('trade_title', models.CharField(default='Trade & Grow', max_length=100)),
                ('trade_desc', models.TextField(default="Whether you're just starting or scaling up, our tools, support, and funding help you grow with confidence.")),
                ('trade_img', models.ImageField(blank=True, null=True, upload_to='section4/')),
            ],
            options={
                'verbose_name': 'Home How_It_Works_Section',
                'verbose_name_plural': 'Home How_It_Works_Section',
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
