# Generated by Django 5.2.5 on 2025-09-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_market_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
