# Generated by Django 5.2.5 on 2025-09-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_readytoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('option_type', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=10)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expiry_date', models.DateField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
