# Generated by Django 5.2.5 on 2025-09-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='presskit/logos/')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='presskit/media/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Press Kit',
                'verbose_name_plural': 'Press Kits',
            },
        ),
    ]
