# Generated by Django 5.2.6 on 2025-09-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_presskit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Investor Page', max_length=140)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('left_title', models.CharField(blank=True, max_length=100)),
                ('left_text', models.TextField(blank=True)),
                ('right_title', models.CharField(blank=True, max_length=100)),
                ('right_text', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='investor/')),
            ],
        ),
    ]
